version: '3.8'

services:
  npc-bot:
    build: ./npc-bot
    container_name: npc_bot
    env_file:
      - ./npc-bot/.env
    restart: unless-stopped
    ipc: host
    extra_hosts:
      - "host.docker.internal:host-gateway"

  website-a-frontend:
    build: ./website-a-frontend
    container_name: website_a_frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
