server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index login.html index.html;

    location /api/ {
        proxy_pass https://steel-mountain-account-recovery.onrender.com/api/;
        proxy_set_header Host steel-mountain-account-recovery.onrender.com;
        proxy_ssl_server_name on;
        proxy_ssl_name steel-mountain-account-recovery.onrender.com;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri.html $uri/ /login.html;
    }
}
